services:
  - type: web
    name: dlfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DLFolio.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
